spring:
  datasource:
    url: jdbc:h2:mem:tacocloud
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org:
      springframework:
        jdbc:
          core: debug # Включает логи для JdbcTemplate
    org.h2: debug       # Логи для H2
